### ISSUE TITLE
Will the model checkpoints be released?

### ISSUE THREAD

**Issue by TheTinyTeddy** [test-time-training/ttt-lm-jax#1]
Hi, thank you for the great work. 

I was wondering whether the model checkpoints will be released for public?

**Comment by karan-dalal** [comment]
Given all our experiments are run on Chinchilla scale (max 26B tokens), model checkpoints will not be useful for real world tasks and generation. However, we can provide checkpoints for specific experiments on a per-request basis. Please email kdalal@berkeley.edu with the requested checkpoint.
