### ISSUE TITLE
Question about equation 7

### ISSUE THREAD

**Issue by shuxiaobo** [test-time-training/ttt-lm-jax#10]
Hi there, when I reading the paper, I'm confused in eqation 7, the $z_t = f(x_t; W_t) = W_t x_t = \left( W_0 - \eta \sum_{s=1}^{t} G_t \right) x_t = W_0 x_t - 2\eta \sum_{s=1}^{t} (W_0 x_s - x_s) x_s^T x_s$，the last two step use x_s replace x_t, I don't know why , is it just approximate?

**Comment by shuxiaobo** [comment]
Another question is Proof of Theorem.1:
<img width="1021" alt="image" src="https://github.com/user-attachments/assets/59a289e1-7a97-45e5-b775-7878f4221f1c">

if $\eta = 1/2 $, Is there still have `2` in the derivative of L ?

**Comment by Z-Z188** [comment]
> Hi there, when I reading the paper, I'm confused in eqation 7, the z t = f ( x t ; W t ) = W t x t = ( W 0 − η ∑ s = 1 t G t ) x t = W 0 x t − 2 η ∑ s = 1 t ( W 0 x s − x s ) x s T x s ，the last two step use x_s replace x_t, I don't know why , is it just approximate?

Hello, I have the same question, do you understand?

**Comment by shuxiaobo** [comment]
In my opinion  that equation 7 can be equivalent to x_t as x_s through a mask operation.

> > Hi there, when I reading the paper, I'm confused in eqation 7, the z t = f ( x t ; W t ) = W t x t = ( W 0 − η ∑ s = 1 t G t ) x t = W 0 x t − 2 η ∑ s = 1 t ( W 0 x s − x s ) x s T x s ，the last two step use x_s replace x_t, I don't know why , is it just approximate?
> 
> Hello, I have the same question, do you understand?
