### ISSUE TITLE
Checkpoint conversion & loading

### ISSUE THREAD

**Issue by juntaic7** [test-time-training/ttt-lm-jax#11]
Hi, when I was trying to convert the jax checkpoints into HF format following [https://gist.github.com/xvjiarui/835bab0a867cd1f4a20714a5f860abfd](url), the two imports doesn't seem to be working:

`from transformers.models.ttt.modeling_ttt import TttForCausalLM`
`from transformers.models.ttt.configuration_ttt import TttConfig`

I also tried to import from ttt.py in ttt-lm-pytorch, but the model sizes doesn't seem to exist in the config. I would appreciate it if you can elaborate more on converting the ckpts!

**Comment by karan-dalal** [comment]
You're supposed to import from ttt.py. Which model sizes are you attempting to run?
