### ISSUE TITLE
GPU Connection

### ISSUE THREAD

**Issue by meichelman** [test-time-training/ttt-lm-jax#12]
Hi,

I would like to evaluate different instantiations of the learner model (i.e. more MLP layers). Is it possible to run the scripts using a remote GPU machine? I understand the directions suggest a local GPU, but I only have access through Secure Shell. When I set up the environment and run the 125m ttt_linear script I get the following error:

<img width="1438" alt="Screenshot 2024-09-26 at 1 30 51 PM" src="https://github.com/user-attachments/assets/31be2c85-0f21-42d9-a57f-bacf52872361">

At the bottom of a long list of traceback calls the final message is:

<img width="1287" alt="Screenshot 2024-09-26 at 1 32 41 PM" src="https://github.com/user-attachments/assets/4f96099b-e240-4ef6-87a9-2babe0a93421">

**Comment by karan-dalal** [comment]
Sorry for the late response. It is possible to run it through a remote GPU machine. However, your issue seems to be with the JAX library. I suggest you make an issue on their GitHub https://github.com/jax-ml/jax
