### ISSUE TITLE
Bucket is a requester pays bucket but no user project provided.

### ISSUE THREAD

**Issue by echolcq** [test-time-training/ttt-lm-jax#15]
Hello! When I run `gsutil -m cp -r gs://llama-2-books3/* llama-2-books3/` to download the provided dataset, I get the message "Bucket is a requester pays bucket but no user project provided."

**Comment by karan-dalal** [comment]
https://github.com/test-time-training/ttt-lm-jax/issues/4#issuecomment-2425233831

**Comment by echolcq** [comment]
你好，我是lynn.邮件已收到！
