### ISSUE TITLE
BadRequestException

### ISSUE THREAD

**Issue by JulietLJY** [test-time-training/ttt-lm-jax#2]
gsutil -m cp -r gs://llama-2-pile/* llama-2-pile/

BadRequestException: 400 Bucket is a requester pays bucket but no user project provided.
CommandException: 1 file/object could not be transferred

**Comment by karan-dalal** [comment]
Hi! In order to make our datasets publicly available, we require the requester to pay for the transfer costs. Please review this link on how to setup a [Google Billing Account](https://cloud.google.com/storage/docs/using-requester-pays#using) to download.
