### ISSUE TITLE
How to download the tokenized books3 dataset? 

### ISSUE THREAD

**Issue by DarthMurse** [test-time-training/ttt-lm-jax#4]
I am very intrigued by the idea presented in TTT and want to reproduce the training process myself. However I encountered some difficulties when downloading the dataset. I've never used google cloud cli before and when I installed the google cloud sdk package and finish the `gcloud init` command, I tried to follow the command provided by the author, but it then gave this error:

```
% gcloud storage cp -r "gs://llama-2-books3/*" llama-2-books3/
Completed files 0 | 0B                                                                                                                                                 
ERROR: (gcloud.storage.cp) HTTPError 400: Bucket is a requester pays bucket but no user project provided.
```

Then I searched online and add an additional parameter to solve this error, but then it gave:

```
% gcloud storage cp -r "gs://llama-2-books3/*" llama-2-books3/ --billing-project=murse1017 
Copying gs://llama-2-books3/tokenizer_name-meta-llama/Llama-2-7b-hf-val_ratio-0.0005-val_split_seed-2357-add_eos-True-detokenize-False/test.npy to file://llama-2-books3/tokenizer_name-meta-llama/Llama-2-7b-hf-val_ratio-0.0005-val_split_seed-2357-add_eos-True-detokenize-False/test.npy
Copying gs://llama-2-books3/tokenizer_name-meta-llama/Llama-2-7b-hf-val_ratio-0.0005-val_split_seed-2357-add_eos-True-detokenize-False/tokenizer.pkl to file://llama-2-books3/tokenizer_name-meta-llama/Llama-2-7b-hf-val_ratio-0.0005-val_split_seed-2357-add_eos-True-detokenize-False/tokenizer.pkl
Copying gs://llama-2-books3/tokenizer_name-meta-llama/Llama-2-7b-hf-val_ratio-0.0005-val_split_seed-2357-add_eos-True-detokenize-False/train.npy to file://llama-2-books3/tokenizer_name-meta-llama/Llama-2-7b-hf-val_ratio-0.0005-val_split_seed-2357-add_eos-True-detokenize-False/train.npy
Copying gs://llama-2-books3/tokenizer_name-meta-llama/Llama-2-7b-hf-val_ratio-0.0005-val_split_seed-2357-add_eos-True-detokenize-False/validation.npy to file://llama-2-books3/tokenizer_name-meta-llama/Llama-2-7b-hf-val_ratio-0.0005-val_split_seed-2357-add_eos-True-detokenize-False/validation.npy
⠧ERROR: HTTPError 403 | 0B/60.7GiB                                                                                                                                       
⠼ Completed files 0/4 | 0B/60.7GiB       
```
And stuck there forever. How can I solve this problem? 
(I've searched a lot of solutions on the Internet but still don't know how to solve this. The google cloud stuff really confused me...)

**Comment by karan-dalal** [comment]
The command provided works on our end. I would suggest trying to re-login to your Google Cloud account, using `gcloud auth login` and then setting the project using `gcloud config set project my-gcp-project`

**Comment by amy-hyunji** [comment]
Hi @karan-dalal 

thank you for sharing the code and dataset!
I am having trouble downloading the dataset. I have gone through the steps you shared and it says

` HTTPError 400: Bucket is a requester pays bucket but no user project provided.`

which it seems like the bucket is not shared or I cannot access them since I am not in the project.
would it be possible to share the dataset by huggingface or could you check if the bucket is accessible by others excluding people who are in the project?
Thank you! :)

**Comment by karan-dalal** [comment]
@amy-hyunji We have enabled requester pays to avoid expensive data costs on our end. Please refer to this link https://cloud.google.com/storage/docs/requester-pays on how to set gcloud up on your end to download the data.
