### ISSUE TITLE
Issue with installing gpu requirements

### ISSUE THREAD

**Issue by meichelman** [test-time-training/ttt-lm-jax#5]
Hi,

I tried to run “pip install -r gpu_requirements.txt” within a conda environment and am running into an issue with the jaxlib installation. numpy, matplotlib, tqdm, torch, and jax are collected without an issue, but I get the error:

ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement jaxlib==0.4.14+cuda12.cudnn89 (from versions: 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.24, 0.4.25, 0.4.26, 0.4.27, 0.4.28, 0.4.29, 0.4.30, 0.4.31)
ERROR: No matching distribution found for jaxlib==0.4.14+cuda12.cudnn89

Any ideas?

**Comment by karan-dalal** [comment]
Does `pip install jaxlib==0.4.14+cuda12.cudnn89 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html` work?

**Comment by meichelman** [comment]
No, I tried that and get the same bottom two errors. Though, the top error about python versions does not appear.

**Comment by karan-dalal** [comment]
Please check your Python version. In order to install this version of JAX, we use Python 3.10. Since you can only find versions 0.4.17+, you might need to downgrade your Python.

You can create a conda env with Python 3.10 as: `conda create -n [env name] python=3.10`

**Comment by meichelman** [comment]
I reinstalled the environment with Python 3.10 (defaulted to 3.10.14) and am getting the same no match error. I am attaching an image of the environment's packages hopefully that will help.
<img width="532" alt="Screenshot 2024-07-30 at 2 49 16 PM" src="https://github.com/user-attachments/assets/2784f217-b038-44c8-a8fd-66e25325c2a8">

**Comment by karan-dalal** [comment]
What happens when you type `python --version` and `pip --version`

Also, would be helpful to always get the full error message.

**Comment by meichelman** [comment]
Yes, sorry about that. The following is the output of the python and pip versions.
% python --version
Python 3.10.14
% pip --version
pip 24.0 from /Users/meichelman/anaconda3/envs/ttt-jax/lib/python3.10/site-packages/pip (python 3.10)

The next two images are the outputs of "pip install jaxlib==0.4.14+cuda12.cudnn89 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html" and "pip install -r gpu_requirements.txt" respectively.

<img width="663" alt="Screenshot 2024-07-30 at 3 30 11 PM" src="https://github.com/user-attachments/assets/d372df25-d227-4668-8290-cb0a2933c46c">



<img width="755" alt="Screenshot 2024-07-30 at 3 31 20 PM" src="https://github.com/user-attachments/assets/d9264e1c-5445-436e-a7a8-64c059b27cf8">

**Comment by karan-dalal** [comment]
Interesting. It seems that you're now able to find version 0.4.14, but still not able to install. Potentially an error with CUDA versioning?

Can you try running `nvcc --version` to check that you are using CUDA 12. Also try `pip install jax==0.4.14 jaxlib==0.4.14`

**Comment by meichelman** [comment]
I think the issue may have to do with CUDA so I tried running on CoLab where I am able to install all of the appropriate versions.
