### ISSUE TITLE
Question about the Figure 19, trying finetuning with TTT layers

### ISSUE THREAD

**Issue by ArtursPark** [test-time-training/ttt-lm-jax#6]
Hello,

Have you tried performing similar pretraining & finetuning with larger context size with TTT layers, and if you saw similar performance improvement as with TF finetune?

Thank you

Great work!

**Comment by ArtursPark** [comment]
Sorry, another thought, you performed a single pass through the tokens, have you tried going through them twice and if that had any significant performance differences?

**Comment by karan-dalal** [comment]
I don't believe we tried either of these experiments. But definitely worth giving a shot!
